name: five_m_stress_relief
description: A 5M Stress Relief Flutter application prototype for Indian students (with MoodMatch API + Firebase).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animations: ^2.0.11
  flutter_animate: ^4.2.0
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1

  # State Management
  provider: ^6.1.1

  # HTTP & WebSocket
  http: ^1.1.1
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  firebase_database: ^11.1.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Supabase
  supabase_flutter: ^2.6.0
  supabase: ^2.2.4
  supabase_auth_ui: ^0.5.5

  # Chat & Social UI
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  flutter_card_swiper: ^7.0.2

  # Maps
  google_maps_flutter: ^2.7.0

  # UI packages
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  lottie: ^2.6.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.1.0

  # Audio
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    
  