// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'GEMINI_API_KEY',
    appId: '1:429012706798:web:1529323fc1114f18b65aff',
    messagingSenderId: '429012706798',
    projectId: 'moodmatch-ea4c7',
    authDomain: 'moodmatch-ea4c7.firebaseapp.com',
    storageBucket: 'moodmatch-ea4c7.firebasestorage.app',
    measurementId: 'G-H15V8KH628',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'GEMINI_API_KEY',
    appId: '1:429012706798:android:b6edbfc921b200cab65aff',
    messagingSenderId: '429012706798',
    projectId: 'moodmatch-ea4c7',
    storageBucket: 'moodmatch-ea4c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'GEMINI_API_KEY',
    appId: '1:429012706798:ios:d3221e8e80ffa130b65aff',
    messagingSenderId: '429012706798',
    projectId: 'moodmatch-ea4c7',
    storageBucket: 'moodmatch-ea4c7.firebasestorage.app',
    iosBundleId: 'com.example.fiveMStressRelief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'GEMINI_API_KEY',
    appId: '1:429012706798:ios:d3221e8e80ffa130b65aff',
    messagingSenderId: '429012706798',
    projectId: 'moodmatch-ea4c7',
    storageBucket: 'moodmatch-ea4c7.firebasestorage.app',
    iosBundleId: 'com.example.fiveMStressRelief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'GEMINI_API_KEY',
    appId: '1:429012706798:web:a8b16dfbc2fa77fdb65aff',
    messagingSenderId: '429012706798',
    projectId: 'moodmatch-ea4c7',
    authDomain: 'moodmatch-ea4c7.firebaseapp.com',
    storageBucket: 'moodmatch-ea4c7.firebasestorage.app',
    measurementId: 'G-93QH8DVC9N',
  );

}
